language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t cbelogu/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true cbelogu/react-test npm test

after_success:
  - docker build -t cbelogu/multi-client ./client
  - docker build -t cbelogu/multi-nginx ./nginx
  - docker build -t cbelogu/multi-server ./server
  - docker build -t cbelogu/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push cbelogu/multi-client
  - docker push cbelogu/multi-nginx
  - docker push cbelogu/multi-server
  - docker push cbelogu/multi-worker